#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

cd mesh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/polyMesh p.foam
cleanCase

cd ..

# ----------------------------------------------------------------- end-of-file

