#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0
rm -rf constant/triSurface/*Scaled.stl
rm -rf constant/triSurface/farfield.stl
rm -rf constant/triSurface/combined.stl
cleanCase
