#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication fluent3DMeshToFoam fluentMesh/agardb2-29.msh -scale 0.001
# runApplication checkMesh


# ----------------------------------------------------------------- end-of-file
