#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


rm -rf 0 constant/polyMesh logs p.foam
cleanCase


# -----------------------------------------------------------------%
