#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd simulation

refineMeshByCellSet()
{
   while [ $# -ge 1 ]
   do
      if [ ! -e log.refineMesh.$1 ]
      then
          echo "creating cell set for primary zone - $1"
          cp system/topoSetDict.$1 system/topoSetDict
          topoSet > log.topoSet.$1 2>&1

          echo "refining primary zone - $1"
          refineMesh -dict system/refineMeshDict -overwrite > log.refineMesh.$1 2>&1
      fi
      shift
   done
}

runApplication blockMesh -dict system/blockMeshDict
refineMeshByCellSet 1 2

rm -rf 0
cp -r 0.org 0

# Parallel ............................
runApplication decomposePar
mpirun -n `getNumberOfProcessors` `getApplication` -parallel 2>&1 | tee log.hisa

cd ..
