#!/bin/sh

cd simulation

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f constant/polyMesh/boundary > /dev/null 2>&1
rm -r constant/cellTable > /dev/null 2>&1
rm -rf 0 > /dev/null 2>&1

cd ..

#------------------------------------------------------------------------------
