#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd simulation

# Get application name
application=`getApplication`

runApplication star4ToFoam -scale 1 ../mesh/nacaAirfoil

sed -i -e 's/symmetry\([)]*;\)/empty\1/' constant/polyMesh/boundary

cp -rf 0.org 0

# Serial ..............................
# runApplication `getApplication`
`getApplication` | tee log.`getApplication`


cd ..

#------------------------------------------------------------------------------
