#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd fixed

rm -rf 0 constant/polyMesh
cleanCase

cd ..

# ----------------------------------------------------------------- end-of-file
