#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

MESH=mesh

cd fixed

foamCleanTutorials

echo 'Create symbolic links to polyMesh in' $MESH
cd constant
mkdir polyMesh
cd polyMesh
for f in ../../../../$MESH/constant/polyMesh/*
do
    ln -s $f .
done
cd ../..

if [ ! -f constant/polyMesh/pointLevel ] || [ ! -f constant/polyMesh/cellLevel ]
then
    echo "Error: Mesh does not contain cellLevel and pointLevel fields which are needed for adaptive refinement." 1>&2
    echo "       Please ensure the mesh was generated using the HiSA fork of cfMesh available from https://gitlab.com/hisa/cfMesh, and not the standard version." 1>&2
    exit 1
fi

if [ -z "$FOAM_API" ] && ( [ "$WM_PROJECT_VERSION" == "dev" ] || [ "$WM_PROJECT_VERSION" -ge "10" ] )
then
    echo "type internal;" > 0.org/include/helperPatchFieldType
else
    echo "type fixedValue;" > 0.org/include/helperPatchFieldType
fi

rm -rf 0
cp -r 0.org 0

# Parallel ............................
runApplication decomposePar
mpirun -n `getNumberOfProcessors` `getApplication` -parallel 2>&1 | tee log.hisa

# Reconstruct
if [ -z "$FOAM_API" ]
then
    runApplication reconstructParMesh -latestTime
    runApplication reconstructPar -latestTime
else
    runParallel redistributePar -reconstruct -latestTime -overwrite
fi

# -----------------------------------------------------------------%
