#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Icem mesh ...............................................
cd icemMesh
runApplication fluent3DMeshToFoam fluentMesh/agardb2-29.msh -scale 0.001

# Icem and cf mesh ........................................
runApplication createPatch -overwrite
runApplication checkMesh

cd ..

# ----------------------------------------------------------------- end-of-file
